-- Supabase/PostgreSQL schema for the GitHub Pages reservation app.
-- Run this file in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'reservation_status') then
    create type reservation_status as enum ('Pending', 'Confirmed', 'Paid', 'Cancelled');
  end if;
end $$;

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  guest_full_name text not null,
  guest_phone text not null,
  guest_email text not null,
  adults integer not null default 1,
  children integer not null default 0,
  check_in date not null,
  check_out date not null,
  nights integer generated always as ((check_out - check_in)) stored,
  total_amount numeric(10, 2) not null default 0.00,
  deposit_paid numeric(10, 2) not null default 0.00,
  remaining_amount numeric(10, 2) generated always as (greatest(0.00, total_amount - deposit_paid)) stored,
  status reservation_status not null default 'Pending',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservations_dates_check check (check_out > check_in),
  constraint reservations_guests_check check (adults >= 1 and children >= 0),
  constraint reservations_amounts_check check (total_amount >= 0 and deposit_paid >= 0)
);

create index if not exists reservations_dates_idx on public.reservations (check_in, check_out);
create index if not exists reservations_status_idx on public.reservations (status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at
before update on public.reservations
for each row
execute function public.set_updated_at();

alter table public.reservations enable row level security;

-- GitHub Pages is a static host, so this app uses the public anon key from the browser.
-- These policies make the table editable by the app without a paid server.
-- For private production use, add Supabase Auth and replace these policies with owner-only rules.
drop policy if exists "Allow public reservation reads" on public.reservations;
create policy "Allow public reservation reads"
on public.reservations for select
to anon
using (true);

drop policy if exists "Allow public reservation inserts" on public.reservations;
create policy "Allow public reservation inserts"
on public.reservations for insert
to anon
with check (true);

drop policy if exists "Allow public reservation updates" on public.reservations;
create policy "Allow public reservation updates"
on public.reservations for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public reservation deletes" on public.reservations;
create policy "Allow public reservation deletes"
on public.reservations for delete
to anon
using (true);
