-- Schéma Supabase/PostgreSQL pour l'application statique GitHub Pages.
-- Exécutez ce fichier dans Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'reservation_status') then
    create type reservation_status as enum ('Pending', 'Confirmed', 'Paid', 'Arrived', 'Departed', 'Cancelled');
  end if;
end $$;

alter type reservation_status add value if not exists 'Arrived';
alter type reservation_status add value if not exists 'Departed';

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  guest_full_name text not null,
  guest_phone text,
  guest_email text,
  whatsapp_number text,
  arrival_time time,
  gps_location text,
  booking_source text not null default 'Direct',
  adults integer not null default 1,
  children integer not null default 0,
  check_in date not null,
  check_out date not null,
  nights integer generated always as ((check_out - check_in)) stored,
  total_amount numeric(10, 2) not null default 0.00,
  deposit_paid numeric(10, 2) not null default 0.00,
  remaining_amount numeric(10, 2) generated always as (greatest(0.00, total_amount - deposit_paid)) stored,
  wassim_concierge_cost numeric(10, 2) not null default 0.00,
  net_profit numeric(10, 2) generated always as (total_amount - wassim_concierge_cost) stored,
  status reservation_status not null default 'Pending',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservations_dates_check check (check_out > check_in),
  constraint reservations_guests_check check (adults >= 1 and children >= 0),
  constraint reservations_amounts_check check (total_amount >= 0 and deposit_paid >= 0 and wassim_concierge_cost >= 0),
  constraint reservations_source_check check (booking_source in ('TunRooms', 'Kabilys', 'Vivlio', 'Instagram', 'Direct', 'WhatsApp'))
);

alter table public.reservations
  alter column guest_phone drop not null,
  alter column guest_email drop not null;

alter table public.reservations add column if not exists whatsapp_number text;
alter table public.reservations add column if not exists arrival_time time;
alter table public.reservations add column if not exists gps_location text;
alter table public.reservations add column if not exists booking_source text not null default 'Direct';
alter table public.reservations add column if not exists wassim_concierge_cost numeric(10, 2) not null default 0.00;
alter table public.reservations add column if not exists net_profit numeric(10, 2) generated always as (total_amount - wassim_concierge_cost) stored;

update public.reservations
set booking_source = 'Direct'
where booking_source is null or booking_source = '';

alter table public.reservations drop constraint if exists reservations_amounts_check;
alter table public.reservations add constraint reservations_amounts_check check (total_amount >= 0 and deposit_paid >= 0 and wassim_concierge_cost >= 0);

alter table public.reservations drop constraint if exists reservations_source_check;
alter table public.reservations add constraint reservations_source_check check (booking_source in ('TunRooms', 'Kabilys', 'Vivlio', 'Instagram', 'Direct', 'WhatsApp'));

create index if not exists reservations_dates_idx on public.reservations (check_in, check_out);
create index if not exists reservations_status_idx on public.reservations (status);
create index if not exists reservations_source_idx on public.reservations (booking_source);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at
before update on public.reservations
for each row
execute function public.set_updated_at();

alter table public.reservations enable row level security;

-- GitHub Pages est un hébergeur statique : l'application utilise la clé anon publique dans le navigateur.
-- Ces politiques rendent la table modifiable par l'application sans serveur payant.
-- Pour une production privée, ajoutez Supabase Auth et remplacez ces politiques par des règles par propriétaire.
drop policy if exists "Allow public reservation reads" on public.reservations;
create policy "Allow public reservation reads"
on public.reservations for select
to anon
using (true);

drop policy if exists "Allow public reservation inserts" on public.reservations;
create policy "Allow public reservation inserts"
on public.reservations for insert
to anon
with check (true);

drop policy if exists "Allow public reservation updates" on public.reservations;
create policy "Allow public reservation updates"
on public.reservations for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public reservation deletes" on public.reservations;
create policy "Allow public reservation deletes"
on public.reservations for delete
to anon
using (true);
